import type { NextApiRequest, NextApiResponse } from 'next';

import jackson from '@lib/jackson';
import { setErrorCookie } from '@lib/utils';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const { method } = req;

  try {
    if (method !== 'POST') {
      throw { message: `Method ${method} Not Allowed`, statusCode: 405 };
    }

    const { oauthController, samlFederated } = await jackson();

    const { SAMLResponse, RelayState, idp_hint } = req.body as {
      SAMLResponse: string;
      RelayState: string;
      idp_hint: string;
    };

    // If RelayState starts "federated_saml_", it's the part of federated SAML login flow.
    if (RelayState.startsWith('federated_saml_')) {
      const { htmlForm } = await samlFederated.sso.generateSAMLResponse({
        response: SAMLResponse,
        relayState: RelayState,
      });

      return res.send(htmlForm);
    }

    // Handle SAML Response generated by IdP
    const { redirect_url, app_select_form } = await oauthController.samlResponse({
      SAMLResponse,
      RelayState,
      idp_hint,
    });

    if (redirect_url) {
      return res.redirect(302, redirect_url);
    }

    if (app_select_form) {
      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      return res.send(app_select_form);
    }
  } catch (error: any) {
    const { message, statusCode = 500 } = error;

    setErrorCookie(res, { message, statusCode }, { path: '/error' });

    return res.redirect('/error');
  }
}
