services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '123ABabc!'
  #      docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=<password>" \
  #      --shm-size 1g \
  #      -p 1433:1433 \
  #      --name sql19 \
  #      --hostname sql19 \
  #      -d mcr.microsoft.com/mssql/server:2019-latest
