FROM runner AS uffizzi
USER root
COPY --from=builder /app/uffizzi/saml_config ./uffizzi/saml_config

COPY ./uffizzi/docker-entrypoint.sh .
RUN chmod +x docker-entrypoint.sh

USER nextjs

CMD ["./docker-entrypoint.sh"]